### ISSUE TITLE
[migrate] Replace `$: {}` with `$effect.pre()` instead of legacy `run()`

### ISSUE THREAD

**Issue by akku1139** [sveltejs/cli#351]
When I run `$ bunx sv migrate svelte-5`
This code
```js
$: {
  ...code...
}
```
was converted to:
```js
import { run } from 'svelte/legacy'
run(() => {
  ...code...
})
```
However, since `run()` is a legacy API, it should be converted to the newer `$effect.pre()` .
```js
$effect.pre(() => {
  ...code...
})
```

**Comment by MotionlessTrain** [comment]
That is intended. run() is specifically made for migrations

The reason is that $: runs on the server, during ssr. $effect.pre() does not.
If ssr is not an issue in your use case, you can just replace it yourself. If not, you may need to rewrite that part of the code. (As svelte cannot guess whether it would be an issue or not, it won’t insert an effect)
