### ISSUE TITLE
Rename 'adders' to add-ons

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/cli#82]
An adder is a type of snake. More generously, it's a thing that adds, not the thing being added.

'Plugins' is probably the right name, since it can cover both integrations with external libraries _and_ things that affect the behaviour of an app without relying on libraries (like, idk, adding some logging middleware), which may become more relevant if we add plugin hooks to SvelteKit in future

**Comment by benmccann** [comment]
I _really_ don't like "extension". Everywhere I've heard that term, it's synonymous with plugin. These aren't extensions in the sense of browser extensions or VS Code extensions since there's no SvelteKit extension API that these are leveraging.

Back to the thesaurus game: `sweetners`, `additions`, `renovations`

**Comment by rdytogokev** [comment]
Is `packages` too generic? 

This is, in fact, what would be added. It would account for any purpose, from a lonely 'robots.txt' file to a full-on middleware.
